CREATE OR REPLACE TRIGGER DISPLAY_CHANGES
BEFORE UPDATE ON challan_bill 
FOR EACH ROW
DECLARE
BEGIN
DBMS_OUTPUT.PUT_LINE('OLD CUSTOMER ADHAR NUMBER'||:OLD.adhar_number);
DBMS_OUTPUT.PUT_LINE('NEW CUSTOMER ADHAR NUMBER'||:NEW.adhar_number);
END;
/
